name: mesovar
channels:
 - conda-forge
dependencies:
 - python=3.6*
 - pangeo-notebook=2020.11.06
 - pip=20
 - awscli
 - bottleneck
 - boto3
 - cartopy>=0.18
 - cfgrib
 - ciso
 - dask-gateway>=0.9
 - dask-ml
 - datashader>=0.11
 - descartes
 - eofs
 - esmpy
 - fastjmd95
 - fsspec
 - gcsfs
 - geopandas
 - geoviews-core
 - gsw
 - h5netcdf
 - h5py
 - holoviews
 - hvplot
 - intake
 - intake-esm
 - intake-geopandas
 - intake-stac
 - intake-xarray
 - ipyleaflet
 - ipywidgets
 - jupyter-panel-proxy
 - lz4
 - matplotlib-base
 - metpy
 - nb_conda_kernels
 - nbstripout
 - nc-time-axis
 - netcdf4
 - nomkl
 - numcodecs
 - numpy
 - pandas
 - panel
 - prefect
 - pyarrow
 - pycamhd
 - pydap
 - pystac
 - python-blosc
 - python-gist
 - rasterio
 - rio-cogeo
 - rioxarray
 - s3fs
 - sat-search
 - sat-stac
 - satpy
 - scikit-image
 - scikit-learn
 - scipy
 - sparse
 - tiledb-py
 - xarray
 - xarray-spatial
 - xesmf
 - xpublish
 - zarr
